SCRIPTS_ROOT_FOLDER = r'D:\TEMP\Scripts'
MODELS_ROOT_FOLDER = r'D:\USUARIS\victor.mas\CitEffect\gitmodel'
ACONSOLE_PATH = r'D:\SOFT\TSS-Transport Simulation Systems\Aimsun 8.0 x64\aconsole.exe'
AIMSUN_SCRIPT_PATH = r'server\external\aimsun_servr.py'
PIPELINES_ROOT_FOLDER = r'D:\TEMP\Pipelines'
